site_name: My Docs
theme:
    name: material
nav:
  - Home: # your existing pages…
      - index.md
# !!! EMBEDDED DOKKA START, DO NOT COMMIT !!! #
  - Reference:
      - api/index.md
# !!! EMBEDDED DOKKA END, DO NOT COMMIT !!! #
