org.gradle.jvmargs=-Xmx8G
kotlin.incremental=false
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true

mod_id=archie
mod_group=net.kernelpanicsoft.archie
mod_version=1.0.0-SNAPSHOT
mod_display_name=Archie
mod_description=A library mod for Kernel Panic's mods
mod_authors=Kernel Panic
mod_credits=Both the NeoForge and fabric teams for the code I ported to Architectury and Kotlin
mod_url=https://github.com/kernel-panic-codecave/Archie
mod_source=https://github.com/kernel-panic-codecave/Archie
mod_issues=https://github.com/kernel-panic-codecave/Archie/issues
mod_license=GPL-3.0-or-later

client_datagen=true
server_datagen=true
