package net.kernelpanicsoft.archie.gui.modifiers.input

/**
 * Base class for all events dispatched through the composable input system.
 *
 * Events propagate through the node tree from the innermost child outward. Once
 * [consume] is called the propagation stops for most event types. The [bypassSuper]
 * flag additionally controls whether the originating [net.minecraft.client.gui.screens.Screen]
 * method forwards the event to its Minecraft `super` implementation.
 */
sealed class InputEvent {
    /**
     * Whether this event has been consumed by a handler.
     *
     * Consumed events do not continue propagating to outer nodes.
     */
    internal var isConsumed: Boolean = false
        private set

    /**
     * When `true`, the screen method that triggered this event will bypass the Minecraft
     * `super` call (i.e. return `true` to absorb the input at the screen level).
     */
    internal var bypassSuper: Boolean = false
        private set

    /**
     * Marks this event as consumed, stopping further propagation.
     *
     * @param bypassSuperCall When `true`, the corresponding screen method will return `true`
     *   instead of delegating to the `super` implementation. Use this when the UI has fully
     *   handled a keyboard or mouse event and the vanilla logic should be suppressed.
     */
    fun consume(bypassSuperCall: Boolean = false) {
        isConsumed = true
        bypassSuper = bypassSuperCall
    }
}

/** GLFW mouse button numbers, plus the value events that no button produced carry. */
object MouseButton {
    /** No button - what a hover, move or scroll event reports. */
    const val NONE = -1

    /** The primary button. */
    const val LEFT = 0

    /** The secondary button. */
    const val RIGHT = 1

    /** The wheel button. */
    const val MIDDLE = 2
}

/**
 * Base class for all pointer (mouse) events.
 *
 * @property type   The specific kind of pointer interaction.
 * @property mouseX The current cursor x position in screen pixels.
 * @property mouseY The current cursor y position in screen pixels.
 * @property button The [MouseButton] the event came from, or [MouseButton.NONE] for an event no
 *   button produced (hover, move, scroll).
 */
sealed class PointerEvent(
    val type: PointerEventType,
    val mouseX: Double,
    val mouseY: Double,
    val button: Int = MouseButton.NONE,
) : InputEvent()

/** A basic pointer event carrying position, type and, for a press or release, the [MouseButton] it came from. */
class BasicPointerEvent(
    type: PointerEventType,
    mouseX: Double,
    mouseY: Double,
    button: Int = MouseButton.NONE,
) : PointerEvent(type, mouseX, mouseY, button)

/**
 * A pointer event generated by mouse wheel movement.
 *
 * @property scrollX Horizontal scroll delta.
 * @property scrollY Vertical scroll delta.
 */
class ScrollEvent(
    type: PointerEventType = PointerEventType.SCROLL,
    mouseX: Double,
    mouseY: Double,
    val scrollX: Double,
    val scrollY: Double,
) : PointerEvent(type, mouseX, mouseY)

/**
 * A pointer event generated by click-dragging the mouse.
 *
 * @property dragX Horizontal drag delta since the last frame.
 * @property dragY Vertical drag delta since the last frame.
 */
class DragEvent(
    type: PointerEventType = PointerEventType.DRAG,
    mouseX: Double,
    mouseY: Double,
    button: Int,
    val dragX: Double,
    val dragY: Double,
) : PointerEvent(type, mouseX, mouseY, button)

/**
 * An event generated by a keyboard key press.
 *
 * @property keyCode   The GLFW key code.
 * @property scanCode  The platform-specific scan code.
 * @property modifiers Bitmask of active modifier keys (Shift / Ctrl / Alt).
 */
data class KeyEvent(
    val keyCode: Int,
    val scanCode: Int,
    val modifiers: Int,
) : InputEvent()

/**
 * An event generated when a printable character is typed.
 *
 * @property codePoint The typed character as a Unicode code point.
 * @property modifiers Bitmask of active modifier keys.
 */
data class CharEvent(
    val codePoint: Char,
    val modifiers: Int,
) : InputEvent()
